services:
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    command: fastapi run api/src/main.py --port 8000
    volumes:
      - uploads:/code/uploads

  app:
    build: ./app
    env_file: ./app/.env
    ports:
      - 3000:3000
    depends_on:
      - api

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATASOURCE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

volumes:
  postgres_data:
  uploads:
