services:
  api:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
    command: fastapi run api/main.py --port 8000
    volumes:
      - uploads:/code/uploads

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATASOURCE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

volumes:
  postgres_data:
  uploads:
