services:
  api:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - ollama
    command: fastapi dev api/main.py --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/code/api
      - uploads:/code/uploads
      - shared_volume:/code/shared

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: always
    volumes:
      - ollama_models:/root/.ollama/models
      - shared_volume:/code/shared
    entrypoint: ["/bin/bash", "/code/shared/entrypoint.sh"]

  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATASOURCE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

volumes:
  postgres_data:
  ollama_models:
  uploads:
  shared_volume:
